# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c03338bc5490e4894279945034d8bac46ca540f8f2e5d33ca90840f3d6549e94586fde639aa3c3195d05aefeb8fcc77143a432635f8f8f2eb8d269184ba834ea

test:
  secret_key_base: 4e01539494855340082efa45729d30277a5016518b6ddfa89d82d0ecc22065fbdc7d2ecdf9a4f04c366a18cbbc133d07cdb298f00fbdac4516982bc6b91a5b44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
